FROM eclipse-temurin:21-jre

WORKDIR /usr/src/account-management

COPY target/AccountManagement-1.0-SNAPSHOT.jar /usr/src/account-management/

CMD ["java", "-Xmx64m", "-jar", "/usr/src/account-management/AccountManagement-1.0-SNAPSHOT.jar"]
