
package dtu.ws.fastmoney;

import dtu.ws.fastmoney.BankServiceException;
import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "BankServiceException", targetNamespace = "http://fastmoney.ws.dtu/")
public class BankServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private dtu.ws.fastmoney.BankServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BankServiceException_Exception(String message, dtu.ws.fastmoney.BankServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BankServiceException_Exception(String message, dtu.ws.fastmoney.BankServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: dtu.ws.fastmoney.BankServiceException
     */
    public BankServiceException getFaultInfo() {
        return faultInfo;
    }

}
